services:
  ####################### APPLICATION #######################
  next-pipeline-local-dev:
    container_name: next-pipeline-local-dev
    build:
      context: ../..
      dockerfile: deploy/dev/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
    networks:
      - my-network
    profiles:
      - dev


networks:
  my-network:
    driver: bridge