services:
  next-pipeline-prod:
    container_name: next-pipeline-prod
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    profiles:
      - prod