services:
  ####################### APPLICATION #######################
  next-pipeline-dev.local:
    container_name: next-pipeline-dev.local
    build:
      context: ../..
      dockerfile: deploy/dev.local/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
    networks:
      - my-network
    profiles:
      - dev.local


networks:
  my-network:
    driver: bridge