name: nextjs-ci-cd

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
      # ----------------------------- CHECKOUT
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------- SETUP NODE
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"
          cache: "npm"

      # ----------------------------- INSTALL DEPENDENCIES
      - name: Install dependencies
        run: npm install

      # ----------------------------- RUN TESTS
      - name: Run tests
        run: npm test --if-present

      # ----------------------------- EXTRACT VERSION
      - name: Extract version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "VERSION_TAG=${{ secrets.DOCKERHUB_REPOSITORY }}:${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          echo "LATEST_TAG=${{ secrets.DOCKERHUB_REPOSITORY }}:latest" >> $GITHUB_ENV

      - name: Print version info
        run: |
          echo "VERSION: $VERSION"
          echo "VERSION TAG: $VERSION_TAG"
          echo "LATEST TAG: $LATEST_TAG"

      # ----------------------------- DOCKER SETUP
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ----------------------------- BUILD & PUSH DOCKER IMAGE
      - name: Build & Push Docker image
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@v3
        with:
          file: deploy/prod/Dockerfile
          context: .
          push: true
          tags: |
            ${{ env.VERSION_TAG }}
            ${{ env.LATEST_TAG }}
          build-args: |
            VERSION=${{ env.VERSION }}

      # ----------------------------- DEPLOY TO LIARA
      - name: Deploy to Liara
        # if: startsWith(github.ref, 'refs/tags/v')
        if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-')
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          npm i -g @liara/cli@7
          liara deploy \
            --dockerfile="deploy/prod/Dockerfile" \
            --api-token="$LIARA_TOKEN" \
            --no-app-logs